### ISSUE TITLE
EventType clr20r3,

### ISSUE THREAD

**Issue by eagleamon** [ppatierno/m2mqtt#16]
First, thanks for the library, happy to use it :)

Then, unfortunately I have a weird problem, I use this library in a service that runs on a xp machine, and time and time, the service crashes with the following errors in the Event viewer application log:

```
EventType clr20r3, P1 gdlservice.exe, P2 1.1.0.0, P3 565dded5, P4 m2mqtt, P5 4.1.0.0, P6 55168185, P7 75, P8 1ff, P9 c4pzlpzd1svnr0sthqltbzijfufynlzn, P10 NIL.

For more information, see Help and Support Center at http://go.microsoft.com/fwlink/events.asp.
``` 
source: .NET Runtime 4.0 Error

and 

```
Application: GdlService.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: uPLibrary.Networking.M2Mqtt.Exceptions.MqttClientException
Stack:
   at uPLibrary.Networking.M2Mqtt.Messages.MqttMsgPublish.GetBytes(Byte)
   at uPLibrary.Networking.M2Mqtt.MqttClient.Send(uPLibrary.Networking.M2Mqtt.Messages.MqttMsgBase)
   at uPLibrary.Networking.M2Mqtt.MqttClient.ProcessInflightThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()


For more information, see Help and Support Center at http://go.microsoft.com/fwlink/events.asp.
```

source: .NET Runtime.

Seems to be related to the getBytes, but I don't really see how for now.

**Comment by eagleamon** [comment]
Nobody's got an idea ?
